// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCw85NcFO4c2647U55x00SQwsJBiqAhA24',
    appId: '1:846023580308:web:33f8f45bda94ac95a87281',
    messagingSenderId: '846023580308',
    projectId: 'learningmobile-4861b',
    authDomain: 'learningmobile-4861b.firebaseapp.com',
    storageBucket: 'learningmobile-4861b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCci5MNiaDdDYDbydFL9s6X6z7UzxkKNXw',
    appId: '1:846023580308:android:72da019b5553ce1ba87281',
    messagingSenderId: '846023580308',
    projectId: 'learningmobile-4861b',
    storageBucket: 'learningmobile-4861b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqUxoZSabHMjOnlkez5xh7opO202fZIBQ',
    appId: '1:846023580308:ios:ec4ec5be8ec1044fa87281',
    messagingSenderId: '846023580308',
    projectId: 'learningmobile-4861b',
    storageBucket: 'learningmobile-4861b.appspot.com',
    iosBundleId: 'com.example.learningFlutter2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqUxoZSabHMjOnlkez5xh7opO202fZIBQ',
    appId: '1:846023580308:ios:a63fc7b8e7174ef9a87281',
    messagingSenderId: '846023580308',
    projectId: 'learningmobile-4861b',
    storageBucket: 'learningmobile-4861b.appspot.com',
    iosBundleId: 'com.example.learningFlutter2.RunnerTests',
  );
}
